### ISSUE TITLE
MacBook Pro15,2 profile 

### ISSUE THREAD

**Issue by egore24** [the-darkvoid/XPS9360-macOS#73]
Have you been able to create a MBP15,2 SMBIOS based profile? If so, what are the performance or other differences? I tried by simply creating a different SMBIOS section with Clover Configurator for 15,2 but it would not boot. If the differences are worth it, how would one go about using your repo but with a 15,2 SMBIOS?

Thanks!

**Comment by the-darkvoid** [comment]
I have and I'm running it currently, idea is that the CPU family is closer to what we have in our machines (`i7-8559U` in the MacBook vs `i7-8550U` in the XPS 9360)

First: Make a backup using SuperDuper! or Carbon Copy Cloner 

You need two things:

- macOS High Sierra build 17G2208 (Use [InstallInstallMacOS.py](https://github.com/munki/macadmin-scripts/blob/master/installinstallmacos.py) to get this)
  After that you can install on top of your existing MacOS install, it will act like an update and your settings and applications will stay intact.

- Disable touch-id functionality in the new XPS9360.sh script, otherwise password super-user prompts cause a few seconds beachball freeze every time

**Comment by egore24** [comment]
Reading the readme from that repo, it sounds like HW incompatibility to that build? To install, do I first have to switch to a 15,2 SMBIOS? If so, I tried to, but could not get a boot. I simply used my current Clover setup (yours) and created a new SMBIOS section for a 15,2 using Clover Configurator. Any idea where I may have gone wrong? Thanks.

**Comment by egore24** [comment]
It doesn't look like the 17G2208 build can be downloaded anymore unless from a genuine MBP15,2. Bummer.

**Comment by egore24** [comment]
I was able to find 17G2208 by other means and, now have a 15,2 machine running. Thanks!

**Comment by the-darkvoid** [comment]
@egore24 , the script I linked should have downloaded 17G2208 or newer just fine.

**Comment by the-darkvoid** [comment]
Also, you'd need to update your serial number to match the MacBook15,2 model you selected.
This should come in handy, because Clover Configurator generated a serial number which did not show the proper MacBook model for me in System -> About:

`JHC8: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
JHC9: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
JHCC: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
JHCD: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
JHCF: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
JHD2: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
JHD3: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
JHD4: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
JHD5: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)`

**Comment by egore24** [comment]
Thanks for that. I did use Clover Configurator right away after the OS update and it did provide an accurate SN for the MacBook15,2.
